### ISSUE TITLE
this OSXFUSE library version is incompatible with the OSXFUSE kernel extension

### ISSUE THREAD

**Issue by nagakiran** [tsto/notmuchfs#15]
I was able to compile successfully notmuchfs on MacOS High sierra (10.13.4). But when I tried to mount using the following command

> $ notmuchfs ~/my_notmuchfs_mountpoint \ 
>     -o backing_dir=~/my_notmuchfs_backing \ 
>     -o mail_dir=~/.maildir

Getting the following error:

> this OSXFUSE library version is incompatible with the OSXFUSE kernel extension

Fuse version installed on MacOS is 3.8.2
Any thoughts on how to resolve this?

**Comment by tsto** [comment]
Looks like your FUSE library version is out of sync with kernel. This is not a notmuchfs-specific issue.
