### ISSUE TITLE
build error with notmuch 0.21

### ISSUE THREAD

**Issue by migueldvb** [tsto/notmuchfs#7]
I am getting the warning below (treated as error) when I try to build notmuchfs on Archlinux using make:

```
cc -g -O2 -std=c99 -Wall -Werror -D_FILE_OFFSET_BITS=64   -c -MD -o notmuchfs.o notmuchfs.c
notmuchfs.c: In function ‘notmuchfs_opendir’:
notmuchfs.c:468:8: error: ‘notmuch_query_search_messages’ is deprecated: function deprecated as of libnotmuch 4.3 [-Werror=deprecated-declarations]
        dir_fd->p_messages = notmuch_query_search_messages(dir_fd->p_query);
        ^
In file included from notmuchfs.c:65:0:
/usr/include/notmuch.h:915:1: note: declared here
 notmuch_query_search_messages (notmuch_query_t *query);
 ^
cc1: all warnings being treated as errors
Makefile:37: recipe for target 'notmuchfs.o' failed
make: *** [notmuchfs.o] Error 1
```

**Comment by felixbecker2** [comment]
Me too. The "-Werror=deprecated-declarations"-parameter seems not to be set within the AUR PKGBUILD, so it seems to be an upstream problem.

**Comment by felixbecker2** [comment]
Me too. The "-Werror=deprecated-declarations"-parameter seems not to be set within the AUR PKGBUILD, so it seems to be an upstream problem. -- You should remove the "-Werror"-switch in the Makefile.

A patch is there: http://ix.io/11CU
